AttributeError:
  At attr.py, line 6, in __init__()
