AttributeError:
  At import.py, line 3, in __init__()
