NameError:
  At name.py, line 2, in __init__()
