Start
Exception:
  At raise1.py, line 2, in main()
  At raise1.py, line 5, in __init__()
